export enum ActionTypeKeys {
    ADD_WATCHLIST_TICKER = "ADD_WATCHLIST_TICKER",
    REMOVE_WATCHLIST_TICKER = "REMOVE_WATCHLIST_TICKER",
    ADD_PORTFOLIO_TICKER = "ADD_PORTFOLIO_TICKER",
    EDIT_PORTFOLIO_TICKER = "EDIT_PORTFOLIO_TICKER",
    REMOVE_PORTFOLIO_TICKER = "REMOVE_PORTFOLIO_TICKER",
    GET_LATEST_MARKET_DATA = "GET_LATEST_MARKET_DATA"
}
